### ISSUE TITLE
how to disable type conversion for json objects

### ISSUE THREAD

**Issue by zcaudate** [leafo/pgmoon#104]
is there a way to get the raw string for a query returning a json object?

**Comment by leafo** [comment]
You can turn override [the type deserializer for json](https://github.com/leafo/pgmoon/blob/master/pgmoon/init.moon#L115) in the instance of pgmoon to nil, or you can cast the json object to text in your postgres query.

**Comment by zcaudate** [comment]
sweet that works really well.
