### ISSUE TITLE
Can't auth postgresql 14 : don't know how to auth: 10

### ISSUE THREAD

**Issue by xiangnanscu** [leafo/pgmoon#108]
I upgrade postgresql to 14 and when try to connect encounter:
```
don't know how to auth: 10
```
When I change pg version to 10, it disappears.

**Comment by xiangnanscu** [comment]
I believe the `auth` method needs some upgrade

**Comment by leafo** [comment]
Authentication method 10 is AuthenticationSASL

Reference: https://www.postgresql.org/docs/14/protocol-message-formats.html

**Comment by leafo** [comment]
#101
