### ISSUE TITLE
cosockets are not available in every context

### ISSUE THREAD

**Issue by jerizm** [leafo/pgmoon#11]
Using pgmoon in certain contexts, like init_by_lua, doesn't work because cosockets aren't available there.

https://www.nginx.com/resources/wiki/modules/lua/#cosockets-not-available-everywhere

Would it be worthwhile to check the context in socket.lua/socket.moon? The below has worked for me. 
`if ngx and ngx.get_phase ~= nil and ngx.get_phase() ~= "init" then`

**Comment by leafo** [comment]
You're thinking it should fall back on to using luasocket in that context? Interesting, didn't consider that but it should work.

**Comment by jerizm** [comment]
Yeah I'm not sure what the downsides are but falling back to luasocket works fine.

**Comment by leafo** [comment]
fixed with #20
