### ISSUE TITLE
Support for transactions

### ISSUE THREAD

**Issue by bt-maps** [leafo/pgmoon#113]
Does pgmoon support postgresql transactions when sending multiple queries like below?

local res, num_queries = pg:query([[
  UPDATE accounts SET balance = balance - 100.00  WHERE name = 'Alice';
  UPDATE accounts SET balance = balance - 155.00  WHERE name = 'Bob'; 
]])

Or would we need to use a raw string to wrap the queries with 
BEGIN;
  UPDATE accounts SET balance = balance - 100.00  WHERE name = 'Alice';
  UPDATE accounts SET balance = balance - 155.00  WHERE name = 'Bob'; 
-- etc etc
COMMIT;

**Comment by leafo** [comment]
pgmoon issues the query string exactly as provided to the database server. Both the examples you gave will work. AFAIR postgres will create an implicit transaction for each query sent. If you need explicit control over the transaction then you can use `BEGIN`, etc. as needed.
