### ISSUE TITLE
attempt to call method 'keepalive' (a nil value)

### ISSUE THREAD

**Issue by xiangnanscu** [leafo/pgmoon#120]
I found this commit:
https://github.com/leafo/pgmoon/commit/cbc765ab0c9c3507019dc223b52cda39acfcacbb
the line `return self.sock:keepalive(...)` should be ` return self.sock:setkeepalive(...)`

**Comment by leafo** [comment]
Thanks, should be fixed before new version goes out. Adding a test suite that runs inside of openresty so we can test those codepaths now
