### ISSUE TITLE
lua entry thread aborted: runtime error: attempt to yield across C-call boundary

### ISSUE THREAD

**Issue by mnegovanovic** [leafo/pgmoon#135]
Hi,

openresty 1.21.4.1-1
pgmoon 1.16.0-1

local pgmoon = require("pgmoon")
local pg = pgmoon.new({
  host = "127.0.0.1",
  port = "5432",
  database = "test",
  user = "test",
  password = "test",
  socket_type = "nginx"
})
pg:connect()

I am getting this error in nginx log:

2023/02/18 11:04:27 [error] 159085#0: *63 lua entry thread aborted: runtime error: attempt to yield across C-call boundary

Any ideas of what i might have misconfigured?

Regards

**Comment by leafo** [comment]
What phase are you making the connection in?

**Comment by mnegovanovic** [comment]
Hi

error was on my part ... new connection was being invoked from top level require function. After refactoring a bit i was able to fix it.

Regards
