### ISSUE TITLE
Default pg_hba.conf settings do not work

### ISSUE THREAD

**Issue by karai17** [leafo/pgmoon#19]
The default (at least on Fedora 23) settings for `pg_hba.conf` do not work with pgmoon.

```
# TYPE  DATABASE        USER            ADDRESS                 METHOD
# "local" is for Unix domain socket connections only
local   all             all                                     peer
# IPv4 local connections:
host    all             all             127.0.0.1/32            ident
# IPv6 local connections:
host    all             all             ::1/128                 ident
```

had to be set to:

```
# TYPE  DATABASE        USER            ADDRESS                 METHOD
# "local" is for Unix domain socket connections only
local   all             all                                     trust
# IPv4 local connections:
host    all             all             127.0.0.1/32            trust
# IPv6 local connections:
host    all             all             ::1/128                 trust
```

**Comment by leafo** [comment]
Closing since it's not an issue for pgmoon, but just a tip.

**Comment by vadi2** [comment]
It's a tip to get this working on Ubuntu and Fedora, arguably some of the most popular Linux variants. I'd say it's arguable that when a library doesn't work out of the box on a popular platform, it's going to be an issue for many people trying it, and ignoring the issue just isn't a good thing to do.

**Comment by karai17** [comment]
It would be a good idea to at least note this in the docs so if/when people run into this, there is already an answer readily available.
