### ISSUE TITLE
invalid password packet size(?)

### ISSUE THREAD

**Issue by whodidthis** [leafo/pgmoon#4]
Any time i use pg:connect() on Openresty this pops up on postgres log:

    2014-09-16 17:07:34 UTC LOG:  invalid password packet size

Not sure how it affects though since the queries still work.

edit: i have the default md5 authentication in use

**Comment by dumbuzz** [comment]
Probably find a bug in init.lua: missing "\0" in final auth string.
Correct call should be:
```
self:send_message(MSG_TYPE.password, {
        "md5",
        md5(md5(self.password .. self.user) .. salt),
        "\0"
      })
```
After this fix, error about invalid password packet size dissappear.

P.S. found this solution after looking at source of lua-resty-postgres (https://github.com/azurewang/lua-resty-postgres/blob/master/lib/resty/postgres.lua). 
They use special function for handling cstrings (by the way - not only for auth communication):
```
local function _to_cstring(data)
    return {data, "\0"}
end
```

**Comment by leafo** [comment]
fixed now
