### ISSUE TITLE
how to use bigint

### ISSUE THREAD

**Issue by devvit** [leafo/pgmoon#48]
I use lapis with pgmoon, and I have a table like this

```sql
create table visits (id bigint primary key, ua varchar(255));
```

store one record

```moonscript
visit = Visits\create { id: '811205756297019392', ua: ngx.var.http_user_agent }
```

fetch the record

```moonscript
v = Visits\find '811205756297019392'
print v.id -- 8.1120575629702e+17
```

I try same code with mysql, it's fine.

So, pgmoon is pure lua(jit), has not int64 support?

thanks.

**Comment by devvit** [comment]
Now, I fork pgmoon, modified init.moon from line 68, just work for me

```moonscript
...
[20]: "string" -- int8
...
```

also, I trying

```moonscript
...
[20]: "bigint" -- int8
...
...
type_deserializers: {
  bigint: (val, name) =>
    ffi.cast 'uint64_t', val
}
...
```

any good idea? I dont want to modify sources

**Comment by leafo** [comment]
I think having bigint deseriazed as string is the best approach by default, and if someone wants a different implementation they can provide it themselves.

**Comment by ttfkam** [comment]
Just to round out the discussion for internet searches, Lua 5.3 adds 64-bit numbers. Luajit is still on the 5.1 API with some backports. Anything else as @leafo and you have found requires tradeoffs. If serialized as a string, you can't do any kind of arithmetic operations on it. As an ID, no problem.

**Comment by leafo** [comment]
After some more testing I've decided that making int8 to string is not a good default, it makes queries like `select count(*) ...` return a string. 

Here's how I recommend adding your own deserializer (without modifying code):

```lua
pg:set_type_oid(20, "bignumber")
pg.type_deserializers.bignumber = function(self, value) return value end
pg:query("select my_big_number from some_table")
```

**Comment by ttfkam** [comment]
Good catch. I totally missed that. Alternatively for Google searches, one may cast to text where all-or-nothing solutions don't fit:

> pg:query("select my_big_number::text from some_table")

Any value in a PostgreSQL query can be converted this way if there is a logical conversion defined, and the query result will follow.

**Comment by turbo** [comment]
> adding your own deserializer

@leafo How would one do that in Lapis? I'd like to add handlers for `BIGINT`, `BIGSERIAL` and `UUID` as strings respectively.
