### ISSUE TITLE
keepalive but still say too many clients already

### ISSUE THREAD

**Issue by xiangnanscu** [leafo/pgmoon#64]
In production, I insert 100K+items and `too many clients already` error happens. I want to know:

1. Is this normal? 
2. Should I do something to the connection if errors happen? Currently, I do nothing.

Below is minimum example [here](https://github.com/xiangnanscu/test) . just clone it , config the database and run `mkdir logs tmp && nginx -c nginx.conf -p .`
## pg.lua
```
local pg_driver = require "pgmoon"
local encode = require "cjson.safe".encode
local type = type
local tostring = tostring
local setmetatable = setmetatable
local error = error
local table_concat = table.concat
local string_format = string.format

local CONNECT_TABLE = { 
        host     = "127.0.0.1", 
        port     = 5432, 
        database = "test", 
        user     = 'postgres', 
        password = '111111', }
local CONNECT_TIMEOUT = 3000
local IDLE_TIMEOUT = 10000
local POOL_SIZE = 50

local function query(statement)
    local db, res, ok, err
    db = pg_driver.new(CONNECT_TABLE) -- always success
    db:settimeout(CONNECT_TIMEOUT) 
    res, err = db:connect()
    if not res then
        return nil, err
    end
    res, err =  db:query(statement) 
    if res ~= nil then
        ok, err = db:keepalive(IDLE_TIMEOUT, POOL_SIZE)
        if not ok then
            return nil, 'fail to set_keepalive:'..err
        end
    end
    if err then
        ngx.log(ngx.ERR, statement)
    end
    return res, err
end

local function main()
    
    local res, err = query('drop table if exists t1;create table t1(id INT PRIMARY KEY NOT NULL);')
    if err then
        return ngx.say(err)
    end
    local t = {}
    for i=1,10^4 do
        local res, err = query('insert into t1 (id) values1 (1);') -- invalid syntax to make errors
        if err then
            t[err]= (t[err] or 0) + 1
        end
    end
    ngx.say(encode(t))
end

main()
```
## nginx
```
worker_processes  1;
user root root;

events {worker_connections  1024;}

http {
    lua_code_cache off;
    access_log  logs/access.log;
    error_log  logs/error.log;

    client_body_temp_path tmp/client_body_temp;
    fastcgi_temp_path tmp/fastcgi_temp;
    proxy_temp_path tmp/proxy_temp;
    scgi_temp_path tmp/scgi_temp;
    uwsgi_temp_path tmp/uwsgi_temp;
    

    
    server {
        listen       8888;
        
        location / {
            content_by_lua_file pg.lua;
        }
    }
    
}
```
the browser output:
```
{"ERROR: syntax error at or near \"values1\" (21)":9948,"FATAL: sorry, too many clients already":52}
```

**Comment by leafo** [comment]
if a client is taken out of the collection pool it can't be used until it is put back into it. If you're creating a massive amount of concurrent requests then the pool is constantly empty and so new connections need to be made. You're then hitting postgres' limit for connections.

You can try increasing the maximum connection limit from postgres if you know what kind of traffic to expect in additional to adding rate limiting in your nginx config.

We currently don't have a programmatic way of dealing with the "sorry, too many clients already" error. One option would be to sleep and try again later until we can get a new connection or pull one from the pool.

**Comment by xiangnanscu** [comment]
@leafo  By saying ` so new connections need to be made`, do you mean if the  pool is constantly empty in my example (50 maxium), pgmoon will still try to make a new connection to database instead of simply refusing to do that?
Does the `pool size`  of pgmoon's keepalive function have to (or the recommend way )be smaller than the `max_connections` of postgres?  

```
test=# show max_connections;
 max_connections 
-----------------
 100
(1 row)
```

**Comment by leafo** [comment]
correct, nginx cosockets do not block you from creating a new connection even if the pool is empty. pgmoon doesn't have it's own pooling mechanism, it's directly calling https://github.com/openresty/lua-nginx-module#tcpsocksetkeepalive

**Comment by xiangnanscu** [comment]
Ok, thanks.

**Comment by xiangnanscu** [comment]
@leafo  I suddenly realized I should use `disconnect` when error happens in  `query`. Now I won't get too many clients already error. But I'm not sure whether `disconnect` on error is OK
```lua
local function query(statement)
    local db, res, ok, err
    db = pg_driver.new(CONNECT_TABLE) -- always success
    db:settimeout(CONNECT_TIMEOUT) 
    res, err = db:connect()
    if not res then
        return nil, err
    end
    local a, b, c, d, e =  db:query(statement)
    if a ~= nil and db.sock_type == 'nginx' then
      ok, err = db:keepalive(max_idle_timeout, pool_size)
      if not ok then
        return nil, 'fail to keepalive:'..err
      else
        return a 
      end
    else
      ok, err = db:disconnect() -- non-openresty error
      if not ok then
        return nil, 'fail to disconnect:'..err
      else
        return a, b, c, d, e 
      end
    end
end
```
