### ISSUE TITLE
How to call udf of pg and handle jsonb return value?

### ISSUE THREAD

**Issue by gzliudan** [leafo/pgmoon#67]
I defined many functions which return value is jsonb data type in postgresql. How to call pg's udf and handle jsonb return value in pgmoon?

**Comment by leafo** [comment]
json data should automatically be decoded to a lua table as long as the type of the value is correct coming from postgres. Are you sure it's not accidentally a string when being returning?

**Comment by gzliudan** [comment]
eg:
CREATE OR REPLACE FUNCTION get_my_data () RETURNS JSONB
AS
$BODY$
DECLARE
BEGIN
    RETURN jsonb_build_object('return_code', 0, 'result', '[{"id":"1","name":"test1"},{"id":"2","name":"test2"}]'::JSONB);
END;
$BODY$
LANGUAGE plpgsql;

**Comment by gzliudan** [comment]
Automatically decoded json to lua table is acceptable. But it's better to provide 2 function and let user choose return type is string or lua table.

**Comment by leafo** [comment]
You can cast the value to a string from postgres using `::text`

If you want to disable json deserialization on the lua end, you can run:

```lua
client:set_type_oid(114, nil)
client:set_type_oid(3802, nil)
```

**Comment by gzliudan** [comment]
thank you very much.
