### ISSUE TITLE
error when out of memory

### ISSUE THREAD

**Issue by gzliudan** [leafo/pgmoon#73]
When my server‘s memory is exhausted, pgmoon report below errors:
attempt to get length of local 'err_msg' (a nil value)

2018/08/09 16:15:33 [error] 15433#15433: *9161 recv() failed (104: Connection reset by peer), client: 127.0.0.1, server: localhost, request: "POST /api/test HTTP/1.0", host: "xxx.com"
2018/08/09 16:15:33 [error] 15433#15433: *9161 lua entry thread aborted: runtime error: /usr/local/openresty/site/lualib/pgmoon/init.lua:390: attempt to get length of local 'err_msg' (a nil value)
stack traceback:
coroutine 0:
        /usr/local/openresty/site/lualib/pgmoon/init.lua: in function 'parse_error'
        /usr/local/openresty/site/lualib/pgmoon/init.lua:243: in function 'auth'
        /usr/local/openresty/site/lualib/pgmoon/init.lua:211: in function 'connect'

**Comment by leafo** [comment]
I'm closing out old tickets. I don't think there's much we can do here. Is this an OOM from postgres server or is the lua vm running out of memory?
