### ISSUE TITLE
Empty db.array will not error, but generate invalid SQL

### ISSUE THREAD

**Issue by turbo** [leafo/pgmoon#86]
For postgres, an empty table passed to `db.array` will generate syntactically invalid SQL:

(shortened)

```moon
model\create tags: DB.array data.topics or {}
```

yields

```SQL
INSERT INTO "projects" (<...>, "tags", <...>) VALUES (<...>, ], <...>) RETURNING "id"
```

This fails because it is rejected by PG.

**Comment by leafo** [comment]
there's a separate ticket about this. essentially it's broken because there's no good solution I'm aware of:

https://github.com/leafo/pgmoon/issues/37

There's no syntax to make an empty array that works for any type

**Comment by turbo** [comment]
FWIW, I'd prefer for it to throw an error.
