### ISSUE TITLE
Support for SSL connections

### ISSUE THREAD

**Issue by agersant** [leafo/pgmoon#9]
I am using pgmoon in the context of a Lapis app deployed on Heroku. Postgres databases hosted by Heroku require SSL encryption for remote TCP connections.

Investigating possible fixes, I learned that ngx.socket.tcp does support SSL connections. It was used last year to add support for SSL connections in lua-resty-mysql (see [here](https://github.com/openresty/lua-nginx-module/pull/290#issuecomment-51131620)). Is this a feature that can be added to pgmoon too?

**Comment by 8026787** [comment]
+1

**Comment by leafo** [comment]
Now merged, and in v1.5.0
