### ISSUE TITLE
pgmoon rockspec version 1.10.0-1 pointing to a wrong branch

### ISSUE THREAD

**Issue by lsevero** [leafo/pgmoon#90]
Hello, I needed to use pgmoon with luaossl and I was having issues with pgmoon always requiring luacrypto to work. The problem is that rockspec version 1.10.0-1 is pointing to the v1.9.0 branch, not the v1.10.0 branch with the fix (source https://luarocks.org/manifests/leafo/pgmoon-1.10.0-1.rockspec ).

Installing version 1.10.0-1 from luarocks was downloading the following code https://github.com/leafo/pgmoon/blob/v1.9.0/pgmoon/crypto.lua which will break if you don't have luacrypto installed. luacrypto is compatible only with openssl1.0 which is not available on my docker setup so unfortunately  it is not an option for me.

**Comment by leafo** [comment]
Sorry about that, it's fixed with v1.11.0 which is now out.
