### ISSUE TITLE
New release with last commits

### ISSUE THREAD

**Issue by youkoulayley** [leafo/pgmoon#92]
Hi, 

Is it possible to have a new release of pgmoon in Luarocks with the lasts commit ? Especially :
205dafe Allow for TLS v1.2 when using LuaSec (not OpenResty)

**Comment by leafo** [comment]
Sure thing, v1.11.0 is now out

**Comment by gzliudan** [comment]
We need new package on http://opm.openresty.org/ also.

**Comment by youkoulayley** [comment]
Nice, thank you leafo !
