### ISSUE TITLE
convert_null works wrong

### ISSUE THREAD

**Issue by alexandrim0** [leafo/pgmoon#94]
Hi!

I set convert_null = true but it returns ["NULL"] but not ngx.null
It is completely unusable!
I belive it should not works like that.
May be it broken with pgsql 11?

**Comment by leafo** [comment]
By default convert_null will convert null to the value stored in Postgres.NULL, which is a unique table `{"NULL"}`. If you want to have it convert to something else then you can override the Postgres.NULL value. 

pgmoon is runtime agnostic, so it does not default o use ngx.null

**Comment by alexandrim0** [comment]
Ok, you are right, pgmoon is runtime agnostic and it is good!
But you also use cjson which also have cjson.null user type represents SQL NULL same way as ngx.null does.
I do not like use nullable types in SQL schemas but in some case it is correct design.
pgmoon is the best lib for lua to deal with pgsql, I think.
So, I need simple way to handle NULL with pgsql as I can do with mysql and etc...
And now I should patch this lib to make my code works after migration from mysql to pgsql. It is no good.
I guess, I am not the one who face this.

So, is it possible to choose which way convert_null will works?
Thank you!

**Comment by leafo** [comment]
I'm not sure I follow, you can override which value gets set to null with something like this:

```
local pg = Postgres:new(...)
pg.convert_null = true
pg.NULL = ngx.null
```

**Comment by alexandrim0** [comment]
Great!

This works fine!
It should be in readme, I think.

Thanks, you are the best!
